support mt5 model
mindspore-lab/mindone pull request #622
Opened 2024-08-02 09:42 UTC by WongGawa

# What does this PR do?

Fixes # (issue)

Adds # (feature)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/mindspore-lab/mindone/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the documentation with your changes? E.g. record bug fixes or new features in `What's New`. Here are the
      [documentation guidelines](https://github.com/mindspore-lab/mindcv/wiki/%E6%96%87%E6%A1%A3%E7%BC%96%E5%86%99%E8%A7%84%E8%8C%83)
- [ ] Did you build and run the code without any errors?
- [ ] Did you report the running environment (NPU type/MS version) and performance in the doc? (better record it for data loading, model inference, or training tasks)
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@xxx

2024-08-09 10:44 UTC, tomzw11 approved these changes

2024-08-12 01:52 UTC, wtomin commented on mindone/transformers/README.md
> +
Is `google/mt5-xxl` also supported by calling a single line or the user need to manually conver the weight to safetensors format?

2024-08-12 02:13 UTC, WongGawa commented on mindone/transformers/README.md
> +
The users need to manually convert the weight to safetensors format.
When converting the weight by [huggingface convert](https://huggingface.co/spaces/safetensors/convert), the following error occurred.
<img width="1230" alt="图片" src="https://github.com/user-attachments/assets/991d9a1e-7ccb-4f9b-beb5-8b0f0ac6dbb1">

2024-08-12 02:31 UTC, SamitHuang commented on mindone/transformers/README.md
> +#### google/mt5-small
please allow provide guidance on using mt5-xxl

2024-08-12 02:45 UTC, geniuspatrick requested changes

2024-08-12 02:45 UTC, geniuspatrick commented on mindone/transformers/README.md
撤销对此文件的修改

2024-08-12 06:25 UTC, wtomin approved these changes

2024-08-12 06:25 UTC, SamitHuang approved these changes

2024-08-12 06:30 UTC, geniuspatrick approved these changes

2024-08-12 06:30 UTC, merged