controlnet  canny2img
mindspore-lab/mindone pull request #76
Opened 2023-08-08 09:42 UTC by congw729

2023-08-18 02:00 UTC, DongyaoZhu requested changes
I feel like having controlnet.py with modes "canny", "depth", etc.

2023-08-18 02:00 UTC, DongyaoZhu commented on examples/stable_diffusion_v2/canny2image.py
> +    n_prompt = 'longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality'
plz move to args

2023-08-18 02:00 UTC, DongyaoZhu commented on examples/stable_diffusion_v2/canny2image.py
> +    logger.info('Start do inference')
delete "do"

2023-08-21 03:19 UTC, congw729 commented
> I feel like having controlnet.py with modes "canny", "depth", etc.
Already add params "mode" to control the mode.

2023-08-21 03:37 UTC, wtomin commented
It's better to have a readme file as the tutorial for canny2controlnet, or for the series of controlnet models.

2023-08-21 06:37 UTC, congw729 commented
> It's better to have a readme file as the tutorial for canny2controlnet, or for the series of controlnet models.

Planning to do it after the related codes are merged.

2023-08-22 06:34 UTC, DongyaoZhu approved these changes

2023-08-22 07:35 UTC, merged